config/routes.rb
Cargo::Application.routes.draw do
  resources :dthc_ports

  resources :container_dthcs

  resources :pages

  resources :othc_ports

  resources :container_othcs

  devise_for :users

  
  resources :pod_fesco_int_tariffs

  resources :pol_fesco_int_tariffs

  get "welcome/index"
  resources :othcs do
    get :autocomplete_line_name, :on => :collection
  end
  resources :dthcs do
    get :autocomplete_line_name, :on => :collection
  end

  resources :fesco_int_tariffs do
    get :autocomplete_line_name, :on => :collection
    get :autocomplete_container_name, :on => :collection    
  end

  resources :lines do
    get :autocomplete_line_name, :on => :collection
  end

  resources :containers

  resources :ports

  resources :companies do
    get :autocomplete_country_name, :on => :collection
  end
    
  resources :countries
  
  resources :tariffs do
    get :autocomplete_port_name, :on => :collection    
    get :autocomplete_pol_name, :on => :collection    
    get :autocomplete_pod_name, :on => :collection    
    get :autocomplete_container_name, :on => :collection    
  end
  

  root "tariffs#index"

  

end

app/models/dthc.rb
class Dthc < ActiveRecord::Base
  belongs_to :line
  has_many :container_dthcs
  has_many :containers, :through => :container_dthcs
  has_many :dthc_ports
  has_many :ports, :through => :dthc_ports
  attr_reader :container_tokens, :port_tokens
  
  def container_tokens=(ids)
    self.container_ids = ids.split(",")
  end
  def port_tokens=(ids)
    self.port_ids = ids.split(",")
  end

  scope :container, lambda { |container_id| { :joins => :containers,
      :conditions => { :containers => { :id => container_id } } } }
  scope :port, lambda { |port_id| { :joins => :ports,
      :conditions => { :ports => { :id => port_id } } } }
  scope :container_and_line, -> (container,line) { Dthc.container(container) & Dthc.line(line) }
  scope :port_and_container_and_line, -> (port, container, line) { Dthc.port(port) & Dthc.container(container) & Dthc.line(line) }
      
  def self.line(line)
    if line
      where(line_id: line)
    else
      scoped
    end
  end
  
end

app/controllers/dthcs_controller.rb
class DthcsController < ApplicationController
  before_action :set_dthc, only: [:show, :edit, :update, :destroy]
  autocomplete :line, :name
  
  # GET /dthcs
  # GET /dthcs.json
  def index
    @dthcs = Dthc.all
  end

  # GET /dthcs/1
  # GET /dthcs/1.json
  def show
    @linename = @dthc.line.name if @dthc.line.present?    
  end

  # GET /dthcs/new
  def new
    @dthc = Dthc.new
    @ports = Port.all
    @containers = Container.all
    @lines = Line.all
  end

  # GET /dthcs/1/edit
  def edit
    @ports = Port.all
    @containers = Container.all
    @lines = Line.all
    @linename = @dthc.line.name if @dthc.line.present?
  end

  # POST /dthcs
  # POST /dthcs.json
  def create
    @dthc = Dthc.new(dthc_params)

    respond_to do |format|
      if @dthc.save
        format.html { redirect_to @dthc, notice: 'Dthc was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dthc }
      else
        format.html { render action: 'new' }
        format.json { render json: @dthc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dthcs/1
  # PATCH/PUT /dthcs/1.json
  def update
    respond_to do |format|
      if @dthc.update(dthc_params)
        format.html { redirect_to @dthc, notice: 'Dthc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dthc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dthcs/1
  # DELETE /dthcs/1.json
  def destroy
    @dthc.destroy
    respond_to do |format|
      format.html { redirect_to dthcs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dthc
      @dthc = Dthc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dthc_params
      params.require(:dthc).permit(:port_id, :line_id, :container_id, :price_cents, :price_currency, :container_tokens, :port_tokens,
                                    { container_tokens: []},                                               
                                    { container_ids: []},
                                    { port_tokens: [] },
                                    { port_ids: [] })
    end
end

app/helpers/dthcs_helper.rb
module DthcsHelper
end

app/views/dthcs/_form.html.haml
= form_for @dthc do |f|
  - if @dthc.errors.any?
    #error_explanation
      %h2= "#{pluralize(@dthc.errors.count, "error")} prohibited this container_dthc from being saved:"
      %ul
      - @dthc.errors.full_messages.each do |msg|
        %li= msg
        
  .row
    .large-12.columns
      = f.label :line_name, "Line"
      = f.autocomplete_field :line_name, autocomplete_line_name_dthcs_path, :id_element => "#dthc_line_id", :value => @linename, placeholder: "* Line Name"
      = f.hidden_field :line_id
    .large-12.columns
      = f.label :price_cents, "Price"
      = f.text_field :price_cents, placeholder: "Amount"
    .large-12.columns
      = f.label :price_currency, "Currency"
      = f.text_field :price_currency, value: "USD", placeholder: "Currency"
    .large-12.columns
      = f.label :container_tokens, "Contaiers"
      = f.text_field :container_tokens, "data-pre" => @dthc.containers.map(&:attributes).to_json
    .large-12.columns
      = f.label :port_tokens, "Ports"
      = f.text_field :port_tokens, "data-pre" => @dthc.ports.map(&:attributes).to_json

  .actions
  =  f.submit "Add Item", class: "button expand"

app/views/dthcs/edit.html.haml
<h1>Editing othc</h1>

= render 'form'

%ul.button-group.expand
  = link_to 'Show', @othc, class: "button tiny expand"
  = link_to 'Back', othcs_path, class: "button tiny expand"

app/views/dthcs/index.html.haml
%h1 Listing dthcs
%hr
%table
  %thead
    %tr
      %th Line
      %th Ports
      %th Container
      %th Price
      %th Currency
      %th
      %th
      %th
  %tbody
    - @dthcs.each do |dthc|

      %tr
        %td
          = dthc.line.name if dthc.line.present?
        %td 
          - dthc.ports.each do |port|
            = port.locode
        %td
          - dthc.containers.each do |container|
            = container.code
        %td= dthc.price_cents
        %td= dthc.price_currency
        %td= link_to 'Show', dthc
        %td= link_to 'Edit', edit_dthc_path(dthc)
        %td= link_to 'Destroy', dthc, :method => :delete, :data => { :confirm => 'Are you sure?' }

= link_to 'New Dthc', new_dthc_path, class: "button"

app/views/dthcs/new.html.haml
%h1 New othc

= render 'form'

= link_to 'Back', othcs_path, class: "button tiny expand"

app/views/dthcs/show.html.haml
= notice

%h1 DTHC

%h3
  %strong Line:
  = @linename

%p
  %strong Ports
  - @dthc.ports.each do |port|
    = port.name.to_s

%p
  %strong Container:
  - @dthc.containers.each do |container|
    = container.name.to_s

%p
  %strong Price cents:
  = @dthc.price_cents

%p
  %strong Currency:
  = @dthc.price_currency

%ul.button-group
  %li= link_to 'Edit', edit_dthc_path(@dthc), class: "button tiny"
  %li= link_to 'Back', dthcs_path, class: "button tiny"