config/routes.rb
Cargo::Application.routes.draw do
  resources :dthc_ports

  resources :container_dthcs

  resources :pages

  resources :othc_ports

  resources :container_othcs

  devise_for :users

  
  resources :pod_fesco_int_tariffs

  resources :pol_fesco_int_tariffs

  get "welcome/index"
  resources :othcs do
    get :autocomplete_line_name, :on => :collection
  end
  resources :dthcs do
    get :autocomplete_line_name, :on => :collection
  end

  resources :fesco_int_tariffs do
    get :autocomplete_line_name, :on => :collection
    get :autocomplete_container_name, :on => :collection    
  end

  resources :lines do
    get :autocomplete_line_name, :on => :collection
  end

  resources :containers

  resources :ports

  resources :companies do
    get :autocomplete_country_name, :on => :collection
  end
    
  resources :countries
  
  resources :tariffs do
    get :autocomplete_port_name, :on => :collection    
    get :autocomplete_pol_name, :on => :collection    
    get :autocomplete_pod_name, :on => :collection    
    get :autocomplete_container_name, :on => :collection    
  end
  

  root "tariffs#index"

  

end

app/models/container_othc.rb
class ContainerOthc < ActiveRecord::Base
  belongs_to :container
  belongs_to :othc
end

app/controllers/container_othcs_controller.rb
class ContainerOthcsController < ApplicationController
  before_action :set_container_othc, only: [:show, :edit, :update, :destroy]

  # GET /container_othcs
  # GET /container_othcs.json
  def index
    @container_othcs = ContainerOthc.all
  end

  # GET /container_othcs/1
  # GET /container_othcs/1.json
  def show
  end

  # GET /container_othcs/new
  def new
    @container_othc = ContainerOthc.new
  end

  # GET /container_othcs/1/edit
  def edit
  end

  # POST /container_othcs
  # POST /container_othcs.json
  def create
    @container_othc = ContainerOthc.new(container_othc_params)

    respond_to do |format|
      if @container_othc.save
        format.html { redirect_to @container_othc, notice: 'Container othc was successfully created.' }
        format.json { render action: 'show', status: :created, location: @container_othc }
      else
        format.html { render action: 'new' }
        format.json { render json: @container_othc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /container_othcs/1
  # PATCH/PUT /container_othcs/1.json
  def update
    respond_to do |format|
      if @container_othc.update(container_othc_params)
        format.html { redirect_to @container_othc, notice: 'Container othc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @container_othc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /container_othcs/1
  # DELETE /container_othcs/1.json
  def destroy
    @container_othc.destroy
    respond_to do |format|
      format.html { redirect_to container_othcs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_container_othc
      @container_othc = ContainerOthc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def container_othc_params
      params.require(:container_othc).permit(:container_id, :othc_id)
    end
end

app/helpers/container_othcs_helper.rb
module ContainerOthcsHelper
end

app/views/container_othcs/_form.html.haml
= form_for @container_othc do |f|
  - if @container_othc.errors.any?
    #error_explanation
      %h2= "#{pluralize(@container_othc.errors.count, "error")} prohibited this container_othc from being saved:"
      %ul
        - @container_othc.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :container_id
    = f.number_field :container_id
  .field
    = f.label :othc_id
    = f.number_field :othc_id
  .actions
    = f.submit 'Save'

app/views/container_othcs/edit.html.haml
%h1 Editing container_othc

= render 'form'

= link_to 'Show', @container_othc
\|
= link_to 'Back', container_othcs_path

app/views/container_othcs/index.html.haml
%h1 Listing container_othcs

%table
  %tr
    %th Container
    %th Othc
    %th
    %th
    %th

  - @container_othcs.each do |container_othc|
    %tr
      %td= container_othc.container_id
      %td= container_othc.othc_id
      %td= link_to 'Show', container_othc
      %td= link_to 'Edit', edit_container_othc_path(container_othc)
      %td= link_to 'Destroy', container_othc, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Container othc', new_container_othc_path

app/views/container_othcs/new.html.haml
%h1 New container_othc

= render 'form'

= link_to 'Back', container_othcs_path

app/views/container_othcs/show.html.haml
%p#notice= notice

%p
  %b Container:
  = @container_othc.container_id
%p
  %b Othc:
  = @container_othc.othc_id

= link_to 'Edit', edit_container_othc_path(@container_othc)
\|
= link_to 'Back', container_othcs_path