config/routes.rb
Cargo::Application.routes.draw do
  resources :dthc_ports

  resources :container_dthcs

  resources :pages

  resources :othc_ports

  resources :container_othcs

  devise_for :users

  
  resources :pod_fesco_int_tariffs

  resources :pol_fesco_int_tariffs

  get "welcome/index"
  resources :othcs do
    get :autocomplete_line_name, :on => :collection
  end
  resources :dthcs do
    get :autocomplete_line_name, :on => :collection
  end

  resources :fesco_int_tariffs do
    get :autocomplete_line_name, :on => :collection
    get :autocomplete_container_name, :on => :collection    
  end

  resources :lines do
    get :autocomplete_line_name, :on => :collection
  end

  resources :containers

  resources :ports

  resources :companies do
    get :autocomplete_country_name, :on => :collection
  end
    
  resources :countries
  
  resources :tariffs do
    get :autocomplete_port_name, :on => :collection    
    get :autocomplete_pol_name, :on => :collection    
    get :autocomplete_pod_name, :on => :collection    
    get :autocomplete_container_name, :on => :collection    
  end
  

  root "tariffs#index"

  

end

app/models/tariff.rb
class Tariff < ActiveRecord::Base

  belongs_to :container
  belongs_to :pol, class_name: "Port"
  belongs_to :pod, class_name: "Port"
  validates :pol_id, :pod_id, presence: true
  attr_accessor :container_name, :pol_name, :pod_name  
  def container_name
    container.try(:name)
  end
  def container_name=(name)
    self.container = Containers.find_by_name(name) if name.present?
  end    
  def pol_name
    pol.try(:name)
  end
  def pol_name=(name)
    self.pol = Port.find_by_name("Vlavivostok") if name.present?
  end    
  def pod_name
    pod.try(:name)
  end
  def pod_name=(name)
    self.pod = Port.find_by_name(name) if name.present?
  end
  
  
  
  def rates
    @rates = find_rates
  end
 
  def othc

  end
  
private
  
  def find_rates

    rates = FescoIntTariff.all
    rates = rates.pol_and_pod_and_container(pol_id,pod_id,container_id) if container_id.present?
    rates = rates.pol_and_pod(pol_id,pod_id) unless container_id.present?
    # rates = rates.pol_and_pod_and_full_and_coc_and_line(pol_id,pod_id,full,coc,line_id) unless container_id.present?
    # rates = rates.pod(pod_id)
    # rates = rates.line(line_id)
    # rates = rates.full(full)
    # rates = rates.coc(coc)
    # rates = rates.container(container_id) if container_id.present?
    # rates = rates.pol(pol_id) if pol_id.present?
    # rates = rates.pod(pod_id) if pod_id.present?
    # rates = rates.line(line_id) if line_id.present?
    othc = nil
    dthc = nil
    res = []
    i = 0
    rates.each do |rate|
      containers = rate.containers
      othc = []
      dthc = []
      containers.each do |container|
        othc += Othc.port_and_container_and_line(pol, container, rate.line)
        dthc += Dthc.port_and_container_and_line(pod, container, rate.line)
      end
      othc = othc[0]
      dthc = dthc[0]
      othcprice = othc.price_cents if othc.present?
      dthcprice = dthc.price_cents if dthc.present?
      othcprice ||= 0
      dthcprice ||= 0
      total = othcprice + dthcprice + rate.baf_cents + rate.freight_cents
      res += [rate: rate, othc: othc, dthc: dthc, total: total]
    end
      
    return res
  end 
  
end

app/controllers/tariffs_controller.rb
class TariffsController < ApplicationController
  before_action :set_tariff, only: [:show, :edit, :update, :destroy]
  autocomplete :pol, :name
  autocomplete :pod, :name  
  autocomplete :port, :name  
  autocomplete :container, :name

  def index
    @tariff = Tariff.new
    @tariffs = Tariff.all
    @pols = Port.order(:name).take(10).map(&:name)
    @pods = Port.order(:name).take(10).map(&:name)  
    @containers = Container.order(:name).map(&:name)
    @companies = Company.all
    @about = Page.find_by_permalink("about")
    @title = @about.name if @about.present?
    @content = @about.content if @about.present?
  end

  def new
    @tariff = Tariff.new
  end
  
  def show
    @container = @tariff.container.name if @tariff.container.present?
    @container = "all container types" unless @tariff.container.present?
    @companies = Company.all
    @rates = @tariff.rates 
  end

  def edit
    @container = @tariff.container.name if @tariff.container.present?
    @pol = @tariff.pol.name if @tariff.pol.present?
    @pod = @tariff.pod.name if @tariff.pod.present?
  end

  def create
    @tariff = Tariff.new(tariff_params)
    respond_to do |format|
      if @tariff.save
        format.html { redirect_to @tariff, notice: 'Tariff was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @tariff.update(tariff_params)
        format.html { redirect_to @tariff, notice: 'Tariff was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tariff.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
  
    def set_tariff
      @tariff = Tariff.find(params[:id])
    end
  
    def tariff_params
      params.require(:tariff).permit( :id, :pol_id, :pod_id, :container_id, :full, :coc, :currency, :line_id, :min_price, :max_price )
    end
    
end

app/helpers/tariffs_helper.rb
module TariffsHelper
end

app/views/tariffs/_form.html.erb
<%= form_for(@tariff) do |f| %>
  <% if @tariff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tariff.errors.count, "error") %> prohibited this fesco_int_tariff from being saved:</h2>

      <ul>
      <% @tariff.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="large-3 columns">
      <%= f.autocomplete_field :pol_name,
    autocomplete_port_name_tariffs_path, :id_element =>
    "#tariff_pol_id", :value => @pol, :placeholder => '* Port of Loading' %>
      <%= f.hidden_field :pol_id %>
    </div>
    <div class="large-3 columns">
      <%= f.autocomplete_field :pod_name,
    autocomplete_port_name_tariffs_path, :id_element =>
    "#tariff_pod_id", :value => @pod, :placeholder => '* Port of Destination' %>
      <%= f.hidden_field :pod_id %>
    </div>
    <div class="large-2 columns">
      <%= f.autocomplete_field :container_name,
    autocomplete_container_name_tariffs_path, :id_element =>
    "#tariff_container_id", :value => @container, :placeholder =>
    'Container Types' %>
      <%= f.hidden_field :container_id %>
    </div>
    <div class="large-2 columns">
      <%= f.button :submit %>
    </div>

  </div>






<% end %>

app/views/tariffs/_header.html.haml
%header.bg
  %center
    = image_tag("slide/demo1.jpg")
  .search-tariffs
    .row
      .large-12.columns
        %h1 Get The Best Tariff
        = render 'headerform'

app/views/tariffs/_headerform.html.erb
<%= form_for(@tariff) do |f| %>
  <% if @tariff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tariff.errors.count, "error") %> prohibited this fesco_int_tariff from being saved:</h2>

      <ul>
      <% @tariff.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row collapse">
    <div class="large-4 columns">
      <%= f.autocomplete_field :pol_name,
    autocomplete_port_name_tariffs_path, :id_element =>
    "#tariff_pol_id", :value => @pol, :placeholder => '* Port of Loading' %>
      <%= f.hidden_field :pol_id %>
    </div>
    <div class="large-4 columns">
      <%= f.autocomplete_field :pol_name,
    autocomplete_port_name_tariffs_path, :id_element =>
    "#tariff_pod_id", :value => @pod, :placeholder => '* Port of Destination' %>
      <%= f.hidden_field :pod_id %>
    </div>
    <div class="large-2 columns">
      <%= f.autocomplete_field :container_name,
    autocomplete_container_name_tariffs_path, :id_element =>
    "#tariff_container_id", :value => @container, :placeholder =>
    'Container Types' %>
      <%= f.hidden_field :container_id %>
    </div>
    <div class="large-2 columns">
      <%= f.button :submit, value: "Search", class: "tiny expand" %>
    </div>
  </div>


<% end %>

app/views/tariffs/_top.html.haml
.index
  .company
    .row
      .large-12.columns
        %h3 The best tariffs from the best shipping line
        %ul.medium-block-grid-2.large-block-grid-4
          - @companies.take(4).each do |company|
            %li
              .logo_border
                .logo_wrapper
                  = link_to image_tag(company.logo, width: "300", class: 'logo'), company_path(company.id)

app/views/tariffs/_zaglushka.html.erb
<h3>Select</h3>

<div class="switch">
  <input id="container-full" name="switch-x" type="radio" checked>
  <label for="x" onclick="">Empty</label>
  <input id="container-empty" name="switch-x" type="radio">
  <label for="x1" onclick="">Full</label>
  <span></span>
</div>

<div class="switch">
  <input id="container-soc" name="switch-soc" type="radio" checked>
  <label for="container-soc" onclick="">SOC</label>
  <input id="container-coc" name="switch-soc" type="radio">
  <label for="container-coc" onclick="">COC</label>
  <span></span>
</div>
<hr>
<form class="custom">
  <h3>Shipping line</h3>
  <label>Check these out</label>
  <% @companies.each do |company| %>
    <div>
      <input id="checkbox<%= company.code %>" type="checkbox"><label for="checkbox<%= company.code %>"><%= company.code %></label>
    </div>
  <% end %>
</form>
<hr>
<a href="#" class="button expand">Search</a>

app/views/tariffs/edit.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>Changing Search</h1>
  </div>
</div>

<%= render 'form' %>

<%= link_to 'Show', @tariff %> |
<%= link_to 'Back', tariff_path %>

app/views/tariffs/index.html.haml
- content_for :header do
  = render 'header'

- content_for :top do
  = render 'top'

%h1
  = @title
%hr
  = simple_format @content

app/views/tariffs/new.html.erb
<h1>Search Tariffs</h1>

<%= render 'form' %>

<%= link_to 'Back', fesco_int_tariffs_path %>

app/views/tariffs/show.html.haml
%p#notice= notice

%ul.breadcrumbs
  %li= link_to "Home", root_path
  %li= link_to "Select destination", tariffs_path
  %li.current
    %a{href: "#"} Select tariff
%h1
  %small from
  = @tariff.pol.name
  %small= "(#{@tariff.pol.locode}) to "
  = @tariff.pod.name
  %small= "(#{@tariff.pod.locode})"
%h4
  = @container
  = link_to 'Change Search', edit_tariff_path(@tariff)
%hr

.row.show 
  .medium-3.large-3.columns
    .panel
      = render 'tariffs/zaglushka'
  .medium-9.large-9.columns.list
    - @rates.each do |res|
      - rate = res[:rate]
      - othc = res[:othc]
      - dthc = res[:dthc]
      - total = res[:total]
      %hr
      .panel
        .row
          .small-6.large-3.columns
            %h1
              .logo_border
                .logo_wrapper
                  = link_to (image_tag rate.line.company.logo), company_path(rate.line.company.id), class: "radius"
          .small-6.large-3.columns
            %p 
              Company
            %h3
              =rate.line.company.code
          .small-6.large-3.columns
            %p 
              Line
            %h3
              =rate.line.code
          .small-6.large-3.columns
            %p 
              Total Price
            %h3
              = humanized_money_with_symbol total
        .row
          .small-4.large-3.columns
            %p
              From:
              = @tariff.pol.name
          .small-4.large-3.columns
            %p
              To:
              = @tariff.pod.name
          .small-4.large-6.columns
            %p
              Container: 
              - rate.containers.each do |container|
                = container.code 
        .row
          .large-12.columns
            %h5
              = link_to "Details", "#"
        %hr
        .row
          .small-6.large-3.columns
            %p
              OTHC
            %h4
              = humanized_money_with_symbol othc.price_cents if othc.present?
          .small-6.large-3.columns
            %p
              DTHC
            %h4
              = humanized_money_with_symbol dthc.price_cents if dthc.present?
          .small-6.large-3.columns
            %p
              BAF
            %h4
              = humanized_money_with_symbol rate.baf_cents
          .small-6.large-3.columns
            %p
              Freight
            %h4
              = humanized_money_with_symbol rate.freight_cents