config/routes.rb
Cargo::Application.routes.draw do
  resources :dthc_ports

  resources :container_dthcs

  resources :pages

  resources :othc_ports

  resources :container_othcs

  devise_for :users

  
  resources :pod_fesco_int_tariffs

  resources :pol_fesco_int_tariffs

  get "welcome/index"
  resources :othcs do
    get :autocomplete_line_name, :on => :collection
  end
  resources :dthcs do
    get :autocomplete_line_name, :on => :collection
  end

  resources :fesco_int_tariffs do
    get :autocomplete_line_name, :on => :collection
    get :autocomplete_container_name, :on => :collection    
  end

  resources :lines do
    get :autocomplete_line_name, :on => :collection
  end

  resources :containers

  resources :ports

  resources :companies do
    get :autocomplete_country_name, :on => :collection
  end
    
  resources :countries
  
  resources :tariffs do
    get :autocomplete_port_name, :on => :collection    
    get :autocomplete_pol_name, :on => :collection    
    get :autocomplete_pod_name, :on => :collection    
    get :autocomplete_container_name, :on => :collection    
  end
  

  root "tariffs#index"

  

end

app/models/othc.rb
class Othc < ActiveRecord::Base
  belongs_to :line
  has_many :container_othcs
  has_many :containers, :through => :container_othcs
  has_many :othc_ports
  has_many :ports, :through => :othc_ports
  validates :line_id, :price_currency, presence: true
  monetize :price_cents
  attr_reader :container_tokens, :port_tokens

  def container_tokens=(ids)
    self.container_ids = ids.split(",")
  end
  def port_tokens=(ids)
    self.port_ids = ids.split(",")
  end
  def line_name
    line.try(:name)
  end
  
  def line_name=(name)
    self.line = Line.find_by_name(name) if name.present?
  end

  scope :container, lambda { |container_id| { :joins => :containers,
      :conditions => { :containers => { :id => container_id } } } }
  scope :port, lambda { |port_id| { :joins => :ports,
      :conditions => { :ports => { :id => port_id } } } }
  scope :container_and_line, -> (container,line) { Othc.container(container) & Othc.line(line) }
  scope :port_and_container_and_line, -> (port, container, line) { Othc.port(port) & Othc.container(container) & Othc.line(line) }
      
  def self.line(line)
    if line
      where(line_id: line)
    else
      scoped
    end
  end

end

app/controllers/othcs_controller.rb
class OthcsController < ApplicationController
  before_action :set_othc, only: [:show, :edit, :update, :destroy]
  autocomplete :line, :name
  
  # GET /othcs
  # GET /othcs.json
  def index
    @othcs = Othc.all
  end

  # GET /othcs/1
  # GET /othcs/1.json
  def show
    @linename = @othc.line.name if @othc.line.present?
  end

  # GET /othcs/new
  def new
    @othc = Othc.new
    @ports = Port.all
    @containers = Container.all
    @lines = Line.all
  end

  # GET /othcs/1/edit
  def edit
    @ports = Port.all
    @containers = Container.all
    @lines = Line.all
    @linename = @othc.line.name if @othc.line.present?
  end

  # POST /othcs
  # POST /othcs.json
  def create
    @othc = Othc.new(othc_params)
    respond_to do |format|
      if @othc.save
        format.html { redirect_to @othc, notice: 'Othc was successfully created.' }
        format.json { render action: 'show', status: :created, location: @othc }
      else
        format.html { render action: 'new' }
        format.json { render json: @othc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /othcs/1
  # PATCH/PUT /othcs/1.json
  def update
    respond_to do |format|
      if @othc.update(othc_params)
        format.html { redirect_to @othc, notice: 'Othc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @othc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /othcs/1
  # DELETE /othcs/1.json
  def destroy
    @othc.destroy
    respond_to do |format|
      format.html { redirect_to othcs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_othc
      @othc = Othc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def othc_params
      params.require(:othc).permit( :id, :line_id, :price_cents, :price_currency, :container_tokens, :port_tokens,
                                    { container_tokens: []},                                               
                                    { container_ids: []},
                                    { port_tokens: [] },
                                    { port_ids: [] })
    end

end

app/helpers/othcs_helper.rb
module OthcsHelper
end

app/views/othcs/_form.html.haml
= form_for @othc do |f|
  - if @othc.errors.any?
    #error_explanation
      %h2= "#{pluralize(@othc.errors.count, "error")} prohibited this container_othc from being saved:"
      %ul
      - @othc.errors.full_messages.each do |msg|
        %li= msg
        
  .row
    .large-12.columns
      = f.label :line_name, "Line"
      = f.autocomplete_field :line_name, autocomplete_line_name_othcs_path, :id_element => "#othc_line_id", :value => @linename, placeholder: "* Line Name"
      = f.hidden_field :line_id
    .large-12.columns
      = f.label :price_cents, "Price"
      = f.text_field :price_cents, placeholder: "Amount"
    .large-12.columns
      = f.label :price_currency, "Currency"
      = f.text_field :price_currency, value: "USD", placeholder: "Currency"
    .large-12.columns
      = f.label :container_tokens, "Contaiers"
      = f.text_field :container_tokens, "data-pre" => @othc.containers.map(&:attributes).to_json
    .large-12.columns
      = f.label :port_tokens, "Ports"
      = f.text_field :port_tokens, "data-pre" => @othc.ports.map(&:attributes).to_json

  .actions
  =  f.submit "Add Item", class: "button expand"

app/views/othcs/edit.html.haml
<h1>Editing othc</h1>

= render 'form'

%ul.button-group.expand
  = link_to 'Show', @othc, class: "button tiny expand"
  = link_to 'Back', othcs_path, class: "button tiny expand"

app/views/othcs/index.html.haml
%h1 Listing othcs
%hr
%table
  %thead
    %tr
      %th Line
      %th Ports
      %th Container
      %th Price
      %th Currency
      %th
      %th
      %th
  %tbody
    - @othcs.each do |othc|

      %tr
        %td
          = othc.line.name if othc.line.present?
        %td 
          - othc.ports.each do |port|
            = port.locode
        %td
          - othc.containers.each do |container|
            = container.code
        %td= othc.price_cents
        %td= othc.price_currency
        %td= link_to 'Show', othc
        %td= link_to 'Edit', edit_othc_path(othc)
        %td= link_to 'Destroy', othc, :method => :delete, :data => { :confirm => 'Are you sure?' }

= link_to 'New Othc', new_othc_path, class: "button"

app/views/othcs/new.html.haml
%h1 New othc

= render 'form'

= link_to 'Back', othcs_path, class: "button tiny expand"

app/views/othcs/show.html.haml
= notice

%h1 OTHC

%h3
  %strong Line:
  = @linename

%p
  %strong Ports
  - @othc.ports.each do |port|
    = port.name.to_s

%p
  %strong Container:
  - @othc.containers.each do |container|
    = container.name.to_s

%p
  %strong Price cents:
  = @othc.price_cents

%p
  %strong Currency:
  = @othc.price_currency

%ul.button-group
  %li= link_to 'Edit', edit_othc_path(@othc), class: "button tiny"
  %li= link_to 'Back', othcs_path, class: "button tiny"